//go:build ignore

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package uiast

// Counters and trust signals for the round loop (spec §3.1).
type Diagnostics struct {
	// Collapsed corresponds to the JSON schema field "collapsed".
	Collapsed *bool `json:"collapsed,omitempty"`

	// FallbackReasons corresponds to the JSON schema field "fallback_reasons".
	FallbackReasons []string `json:"fallback_reasons,omitempty"`

	// InputBytes corresponds to the JSON schema field "input_bytes".
	InputBytes *int `json:"input_bytes,omitempty"`

	// LatencyMs corresponds to the JSON schema field "latency_ms".
	LatencyMs *int `json:"latency_ms,omitempty"`

	// OutputBytes corresponds to the JSON schema field "output_bytes".
	OutputBytes *int `json:"output_bytes,omitempty"`

	// Untrusted corresponds to the JSON schema field "untrusted".
	Untrusted *bool `json:"untrusted,omitempty"`
}

// Strict subset of uiast.json for multi-field form widget payloads.
type GenerateForm struct {
	// Schema corresponds to the JSON schema field "schema".
	Schema interface{} `json:"schema"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

// Strict subset of uiast.json for menu/choice widget payloads.
type GenerateMenu struct {
	// Default corresponds to the JSON schema field "default".
	Default *string `json:"default,omitempty"`

	// Max corresponds to the JSON schema field "max".
	Max *int `json:"max,omitempty"`

	// Min corresponds to the JSON schema field "min".
	Min *int `json:"min,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options []GenerateMenuOptionsElem `json:"options"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

type GenerateMenuOptionsElem struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}

// Strict subset of uiast.json for text-input widget payloads.
type GenerateText struct {
	// Default corresponds to the JSON schema field "default".
	Default *string `json:"default,omitempty"`

	// MaxLength corresponds to the JSON schema field "maxLength".
	MaxLength *int `json:"maxLength,omitempty"`

	// Multiline corresponds to the JSON schema field "multiline".
	Multiline *bool `json:"multiline,omitempty"`

	// Placeholder corresponds to the JSON schema field "placeholder".
	Placeholder *string `json:"placeholder,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

// Strict subset of uiast.json for yes/no (binary) widget payloads.
type GenerateYN struct {
	// Default corresponds to the JSON schema field "default".
	Default *string `json:"default,omitempty"`

	// NoLabel corresponds to the JSON schema field "no_label".
	NoLabel *string `json:"no_label,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// YesLabel corresponds to the JSON schema field "yes_label".
	YesLabel *string `json:"yes_label,omitempty"`
}

// UIAST root envelope emitted by the uiadapter translator (spec §3.1).
type UIAST struct {
	// Counters and trust signals for the round loop (spec §3.1).
	Diagnostics Diagnostics `json:"diagnostics"`

	// FallbackAnswerShape corresponds to the JSON schema field
	// "fallback_answer_shape".
	FallbackAnswerShape string `json:"fallback_answer_shape"`

	// GeneratedAt corresponds to the JSON schema field "generated_at".
	GeneratedAt int `json:"generated_at"`

	// GeneratedBy corresponds to the JSON schema field "generated_by".
	GeneratedBy string `json:"generated_by"`

	// Nodes corresponds to the JSON schema field "nodes".
	Nodes []UINode `json:"nodes"`

	// TurnSummary corresponds to the JSON schema field "turn_summary".
	TurnSummary string `json:"turn_summary"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

// Single-struct discriminated-union node variant (spec §3.2).
type UINode struct {
	// Bullets corresponds to the JSON schema field "bullets".
	Bullets []string `json:"bullets,omitempty"`

	// Columns corresponds to the JSON schema field "columns".
	Columns []string `json:"columns,omitempty"`

	// Content corresponds to the JSON schema field "content".
	Content *string `json:"content,omitempty"`

	// Copyable corresponds to the JSON schema field "copyable".
	Copyable *bool `json:"copyable,omitempty"`

	// Heading corresponds to the JSON schema field "heading".
	Heading *string `json:"heading,omitempty"`

	// Help corresponds to the JSON schema field "help".
	Help *string `json:"help,omitempty"`

	// Lang corresponds to the JSON schema field "lang".
	Lang *string `json:"lang,omitempty"`

	// Prompt corresponds to the JSON schema field "prompt".
	Prompt *string `json:"prompt,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required *bool `json:"required,omitempty"`

	// ResponseKey corresponds to the JSON schema field "response_key".
	ResponseKey *string `json:"response_key,omitempty"`

	// Rows corresponds to the JSON schema field "rows".
	Rows [][]string `json:"rows,omitempty"`

	// Tone corresponds to the JSON schema field "tone".
	Tone *string `json:"tone,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// Input-control metadata for decision_group nodes (spec §3.2).
	Widget *WidgetNode `json:"widget,omitempty"`
}

// Input-control metadata for decision_group nodes (spec §3.2).
type WidgetNode struct {
	// Accept corresponds to the JSON schema field "accept".
	Accept []string `json:"accept,omitempty"`

	// Default corresponds to the JSON schema field "default".
	Default *string `json:"default,omitempty"`

	// Max corresponds to the JSON schema field "max".
	Max *int `json:"max,omitempty"`

	// MaxLength corresponds to the JSON schema field "maxLength".
	MaxLength *int `json:"maxLength,omitempty"`

	// Min corresponds to the JSON schema field "min".
	Min *int `json:"min,omitempty"`

	// Multiline corresponds to the JSON schema field "multiline".
	Multiline *bool `json:"multiline,omitempty"`

	// NoLabel corresponds to the JSON schema field "no_label".
	NoLabel *string `json:"no_label,omitempty"`

	// Options corresponds to the JSON schema field "options".
	Options []WidgetOption `json:"options,omitempty"`

	// Placeholder corresponds to the JSON schema field "placeholder".
	Placeholder *string `json:"placeholder,omitempty"`

	// RepoRootRelative corresponds to the JSON schema field "repoRootRelative".
	RepoRootRelative *bool `json:"repoRootRelative,omitempty"`

	// Schema corresponds to the JSON schema field "schema".
	Schema interface{} `json:"schema,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`

	// YesLabel corresponds to the JSON schema field "yes_label".
	YesLabel *string `json:"yes_label,omitempty"`
}

// Single choice entry (spec §3.2).
type WidgetOption struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value"`
}
