<script>
  /** @typedef {import('../../types/uiAst').Diagnostics} Diagnostics */
  import { ShieldAlert, Info, Sparkles, AlertTriangle } from 'lucide-svelte';

  /** @type {Diagnostics | null} */
  export let diagnostics;
  /** @type {string | undefined} */
  export let generatedBy = undefined;

  const UNTRUSTED_TITLE =
    'The adapter may have dropped or altered content. See raw below.';
  const REASONS_CAP = 8;

  $: untrusted = diagnostics?.untrusted === true;
  $: reasons = diagnostics?.fallback_reasons ?? [];
  $: noteCount = reasons.length;
  $: ollamaModel =
    typeof generatedBy === 'string' && generatedBy.startsWith('ollama:')
      ? generatedBy.slice('ollama:'.length)
      : '';
  $: fallbackReason =
    typeof generatedBy === 'string' && generatedBy.startsWith('fallback:')
      ? generatedBy.slice('fallback:'.length)
      : '';
  $: hasAny = !!ollamaModel || !!fallbackReason || untrusted || noteCount > 0;
  $: notesLabel = `${noteCount} adapter ${noteCount === 1 ? 'note' : 'notes'}`;
  $: notesTitle =
    noteCount <= REASONS_CAP
      ? reasons.join(', ')
      : `${reasons.slice(0, REASONS_CAP).join(', ')}…, +${noteCount - REASONS_CAP} more`;
</script>

{#if hasAny}
  <div class="diagnostics" data-testid="diagnostics-chip" role="status">
    {#if ollamaModel}
      <span
        class="chip success"
        title={`Generated by Ollama model ${ollamaModel}`}
        aria-label={`Generated by Ollama model ${ollamaModel}`}
      >
        <span class="icon" aria-hidden="true">
          <Sparkles size={11} />
        </span>
        Ollama · {ollamaModel}
      </span>
    {:else if fallbackReason}
      <span
        class="chip warn"
        title={`Fallback path: ${fallbackReason}. Raw model output is shown below.`}
        aria-label={`Fallback path: ${fallbackReason}`}
      >
        <span class="icon" aria-hidden="true">
          <AlertTriangle size={11} />
        </span>
        Fallback · {fallbackReason}
      </span>
    {/if}
    {#if untrusted}
      <span class="chip warn" title={UNTRUSTED_TITLE} aria-label={UNTRUSTED_TITLE}>
        <span class="icon" aria-hidden="true">
          <ShieldAlert size={11} />
        </span>
        Untrusted
      </span>
    {/if}
    {#if noteCount > 0}
      <span class="chip info" title={notesTitle} aria-label={notesTitle}>
        <span class="icon" aria-hidden="true">
          <Info size={11} />
        </span>
        {notesLabel}
      </span>
    {/if}
  </div>
{/if}

<style>
  .diagnostics {
    display: flex;
    align-items: center;
    gap: var(--sp-xs);
  }

  .chip {
    display: inline-flex;
    align-items: center;
    gap: var(--sp-2xs);
    padding: 0 var(--sp-xs);
    height: var(--chip-height);
    line-height: var(--chip-height);
    border-radius: var(--radius-sm);
    border: 1px solid;
    font-family: var(--font-mono);
    font-size: var(--text-label);
    letter-spacing: 0.05em;
    text-transform: uppercase;
    white-space: nowrap;
  }

  .icon {
    display: inline-flex;
    flex: 0 0 auto;
    align-items: center;
  }

  .chip.warn {
    background: color-mix(in srgb, var(--accent-amber) 15%, transparent);
    color: var(--accent-amber);
    border-color: color-mix(in srgb, var(--accent-amber) 30%, transparent);
    font-weight: 600;
  }

  .chip.info {
    background: color-mix(in srgb, var(--accent-blue) 12%, transparent);
    color: var(--accent-blue);
    border-color: color-mix(in srgb, var(--accent-blue) 25%, transparent);
    font-variant-numeric: tabular-nums;
    font-weight: 500;
    letter-spacing: 0.04em;
  }

  .chip.success {
    background: color-mix(in srgb, var(--accent-green) 12%, transparent);
    color: var(--accent-green);
    border-color: color-mix(in srgb, var(--accent-green) 30%, transparent);
    font-weight: 600;
  }
</style>
