// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExplainDiffHunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainDiffHunk'](arg1, arg2, arg3);
}

export function GetAgentLog(arg1) {
  return window['go']['main']['App']['GetAgentLog'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDevDir() {
  return window['go']['main']['App']['GetDevDir']();
}

export function GetFontsDir() {
  return window['go']['main']['App']['GetFontsDir']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetSavedThemes() {
  return window['go']['main']['App']['GetSavedThemes']();
}

export function GetScopedDiff(arg1) {
  return window['go']['main']['App']['GetScopedDiff'](arg1);
}

export function GetTerminalPort() {
  return window['go']['main']['App']['GetTerminalPort']();
}

export function GetWorktrees(arg1) {
  return window['go']['main']['App']['GetWorktrees'](arg1);
}

export function GitCommit(arg1) {
  return window['go']['main']['App']['GitCommit'](arg1);
}

export function GitCommitAndPush(arg1) {
  return window['go']['main']['App']['GitCommitAndPush'](arg1);
}

export function GitCommitPushAndPR(arg1) {
  return window['go']['main']['App']['GitCommitPushAndPR'](arg1);
}

export function GitCommitStreaming(arg1) {
  return window['go']['main']['App']['GitCommitStreaming'](arg1);
}

export function GitCreateBranch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2, arg3, arg4);
}

export function GitForcePush(arg1) {
  return window['go']['main']['App']['GitForcePush'](arg1);
}

export function GitListBranches(arg1) {
  return window['go']['main']['App']['GitListBranches'](arg1);
}

export function GitMergeInto(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitMergeInto'](arg1, arg2, arg3);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitSwitchBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitSwitchBranch'](arg1, arg2, arg3);
}

export function IsExplainAvailable() {
  return window['go']['main']['App']['IsExplainAvailable']();
}

export function KillAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillAgent'](arg1, arg2, arg3);
}

export function ListLocalFonts() {
  return window['go']['main']['App']['ListLocalFonts']();
}

export function ListNerdFonts() {
  return window['go']['main']['App']['ListNerdFonts']();
}

export function ListRepoChoices() {
  return window['go']['main']['App']['ListRepoChoices']();
}

export function ListRepoFiles(arg1) {
  return window['go']['main']['App']['ListRepoFiles'](arg1);
}

export function ListVSCodiumThemes() {
  return window['go']['main']['App']['ListVSCodiumThemes']();
}

export function MarkRead(arg1) {
  return window['go']['main']['App']['MarkRead'](arg1);
}

export function OpenFontsDir() {
  return window['go']['main']['App']['OpenFontsDir']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileAtHead(arg1, arg2) {
  return window['go']['main']['App']['ReadFileAtHead'](arg1, arg2);
}

export function ReadFileDiff(arg1, arg2) {
  return window['go']['main']['App']['ReadFileDiff'](arg1, arg2);
}

export function ReadThemeFile(arg1) {
  return window['go']['main']['App']['ReadThemeFile'](arg1);
}

export function RemoveTheme(arg1) {
  return window['go']['main']['App']['RemoveTheme'](arg1);
}

export function RepoMtimes(arg1) {
  return window['go']['main']['App']['RepoMtimes'](arg1);
}

export function RepoStatus(arg1) {
  return window['go']['main']['App']['RepoStatus'](arg1);
}

export function SaveTheme(arg1, arg2) {
  return window['go']['main']['App']['SaveTheme'](arg1, arg2);
}

export function SetDevDir(arg1) {
  return window['go']['main']['App']['SetDevDir'](arg1);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetImportedTheme(arg1) {
  return window['go']['main']['App']['SetImportedTheme'](arg1);
}

export function SetMonoFont(arg1) {
  return window['go']['main']['App']['SetMonoFont'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetVSCodiumExtPath(arg1) {
  return window['go']['main']['App']['SetVSCodiumExtPath'](arg1);
}

export function SpawnAgent(arg1, arg2) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2);
}

export function SpawnAgentWithCommand(arg1, arg2) {
  return window['go']['main']['App']['SpawnAgentWithCommand'](arg1, arg2);
}

export function SpawnPRReview(arg1) {
  return window['go']['main']['App']['SpawnPRReview'](arg1);
}

export function SpawnTerminal(arg1) {
  return window['go']['main']['App']['SpawnTerminal'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
