// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevDir() {
  return window['go']['main']['App']['GetDevDir']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetScopedDiff(arg1) {
  return window['go']['main']['App']['GetScopedDiff'](arg1);
}

export function GetTerminalPort() {
  return window['go']['main']['App']['GetTerminalPort']();
}

export function GetWorktrees(arg1) {
  return window['go']['main']['App']['GetWorktrees'](arg1);
}

export function MarkRead(arg1) {
  return window['go']['main']['App']['MarkRead'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function SetDevDir(arg1) {
  return window['go']['main']['App']['SetDevDir'](arg1);
}
