// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetAgentLog(arg1:string):Promise<Array<domain.LogLine>>;

export function GetDevDir():Promise<string>;

export function GetNotifications():Promise<Array<domain.NotificationEvent>>;

export function GetScopedDiff(arg1:string):Promise<domain.ScopedDiff>;

export function GetTerminalPort():Promise<number>;

export function GetWorktrees(arg1:string):Promise<Array<domain.WorktreeInfo>>;

export function ListRepoChoices():Promise<Array<Record<string, string>>>;

export function MarkRead(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function SetDevDir(arg1:string):Promise<void>;

export function SpawnAgent(arg1:string,arg2:string):Promise<string>;
