// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgentLog(arg1) {
  return window['go']['main']['App']['GetAgentLog'](arg1);
}

export function GetDevDir() {
  return window['go']['main']['App']['GetDevDir']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetScopedDiff(arg1) {
  return window['go']['main']['App']['GetScopedDiff'](arg1);
}

export function GetTerminalPort() {
  return window['go']['main']['App']['GetTerminalPort']();
}

export function GetWorktrees(arg1) {
  return window['go']['main']['App']['GetWorktrees'](arg1);
}

export function ListRepoChoices() {
  return window['go']['main']['App']['ListRepoChoices']();
}

export function MarkRead(arg1) {
  return window['go']['main']['App']['MarkRead'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileDiff(arg1, arg2) {
  return window['go']['main']['App']['ReadFileDiff'](arg1, arg2);
}

export function SetDevDir(arg1) {
  return window['go']['main']['App']['SetDevDir'](arg1);
}

export function SpawnAgent(arg1, arg2) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2);
}
