// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetNotifications():Promise<Array<domain.NotificationEvent>>;

export function GetScopedDiff(arg1:string):Promise<domain.ScopedDiff>;

export function GetTerminalPort():Promise<number>;

export function GetWorktrees(arg1:string):Promise<Array<domain.WorktreeInfo>>;

export function MarkRead(arg1:string):Promise<void>;
