// Unified theme definitions for Mashed.
// Each theme has: label, css (custom properties), monaco (editor theme), xterm (terminal theme).

export const themes = {
  'mashed-dark': {
    label: 'Dark',
    css: {
      '--bg-deepest': '#07080a',
      '--bg-surface': '#0d0f12',
      '--bg-elevated': '#12151a',
      '--bg-active': '#181c23',
      '--border-subtle': '#1e2530',
      '--border-emphasis': '#2a3340',
      '--accent-green': '#00e57a',
      '--accent-green-dim': '#006636',
      '--accent-amber': '#f0a500',
      '--accent-red': '#e84545',
      '--accent-blue': '#3d9eff',
      '--accent-purple': '#9d6fff',
      '--accent-teal': '#00c4b3',
      '--text-primary': '#c8d4e0',
      '--text-dim': '#4a5a6a',
      '--text-muted': '#2e3d4d',
    },
    monaco: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '9d6fff', fontStyle: 'bold' },
        { token: 'string', foreground: '00e57a' },
        { token: 'number', foreground: 'f0a500' },
        { token: 'type', foreground: '00c4b3' },
        { token: 'function', foreground: '3d9eff' },
        { token: 'comment', foreground: '5a6a7a', fontStyle: 'italic' },
        { token: 'variable', foreground: 'c8d4e0' },
        { token: 'operator', foreground: 'c8d4e0' },
        { token: 'delimiter', foreground: '8899aa' },
      ],
      colors: {
        'editor.background': '#07080a',
        'editor.foreground': '#c8d4e0',
        'editorCursor.foreground': '#00e57a',
        'editor.selectionBackground': '#1a3a5c',
        'editor.lineHighlightBackground': '#0d1117',
        'editorLineNumber.foreground': '#3a4a5a',
        'editorLineNumber.activeForeground': '#8899aa',
        'editorGutter.background': '#07080a',
        'diffEditor.insertedTextBackground': '#00e57a18',
        'diffEditor.removedTextBackground': '#ff4a4a18',
        'diffEditor.insertedLineBackground': '#00e57a0d',
        'diffEditor.removedLineBackground': '#ff4a4a0d',
        'editorWidget.background': '#0d1117',
        'editorWidget.border': '#1a2332',
        'input.background': '#0d1117',
        'input.border': '#1a2332',
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#1a233280',
        'scrollbarSlider.hoverBackground': '#2a3342',
        'scrollbarSlider.activeBackground': '#3a4352',
      },
    },
    xterm: {
      background: '#07080a',
      foreground: '#c8d4e0',
      cursor: '#00e57a',
      cursorAccent: '#07080a',
      selectionBackground: '#2a3340',
      black: '#07080a',
      red: '#e84545',
      green: '#00e57a',
      yellow: '#f0a500',
      blue: '#3d9eff',
      magenta: '#9d6fff',
      cyan: '#00c4b3',
      white: '#c8d4e0',
    },
  },

  'mashed-light': {
    label: 'Light',
    css: {
      '--bg-deepest': '#f8f9fb',
      '--bg-surface': '#ffffff',
      '--bg-elevated': '#f0f2f5',
      '--bg-active': '#e8ecf0',
      '--border-subtle': '#d0d7e0',
      '--border-emphasis': '#b8c2cc',
      '--accent-green': '#059a50',
      '--accent-green-dim': '#d0f0df',
      '--accent-amber': '#c07800',
      '--accent-red': '#cc3333',
      '--accent-blue': '#2270cc',
      '--accent-purple': '#7044cc',
      '--accent-teal': '#0a8a7a',
      '--text-primary': '#1a1e24',
      '--text-dim': '#4a5568',
      '--text-muted': '#8896a6',
    },
    monaco: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '7044cc', fontStyle: 'bold' },
        { token: 'string', foreground: '059a50' },
        { token: 'number', foreground: 'c07800' },
        { token: 'type', foreground: '0a8a7a' },
        { token: 'function', foreground: '2270cc' },
        { token: 'comment', foreground: '8896a6', fontStyle: 'italic' },
        { token: 'variable', foreground: '1a1e24' },
        { token: 'operator', foreground: '4a5568' },
        { token: 'delimiter', foreground: '6b7a8d' },
      ],
      colors: {
        'editor.background': '#f8f9fb',
        'editor.foreground': '#1a1e24',
        'editorCursor.foreground': '#059a50',
        'editor.selectionBackground': '#c8daf0',
        'editor.lineHighlightBackground': '#f0f2f5',
        'editorLineNumber.foreground': '#b0b8c4',
        'editorLineNumber.activeForeground': '#6b7a8d',
        'editorGutter.background': '#f8f9fb',
        'diffEditor.insertedTextBackground': '#059a5020',
        'diffEditor.removedTextBackground': '#cc333320',
        'diffEditor.insertedLineBackground': '#059a500d',
        'diffEditor.removedLineBackground': '#cc33330d',
        'editorWidget.background': '#ffffff',
        'editorWidget.border': '#d0d7e0',
        'input.background': '#ffffff',
        'input.border': '#d0d7e0',
        'scrollbar.shadow': '#00000008',
        'scrollbarSlider.background': '#b8c2cc60',
        'scrollbarSlider.hoverBackground': '#a0acb8',
        'scrollbarSlider.activeBackground': '#8896a6',
      },
    },
    xterm: {
      background: '#f8f9fb',
      foreground: '#1a1e24',
      cursor: '#059a50',
      cursorAccent: '#f8f9fb',
      selectionBackground: '#c8daf0',
      black: '#1a1e24',
      red: '#cc3333',
      green: '#059a50',
      yellow: '#c07800',
      blue: '#2270cc',
      magenta: '#7044cc',
      cyan: '#0a8a7a',
      white: '#f8f9fb',
    },
  },

  'mashed-midnight': {
    label: 'Midnight',
    css: {
      '--bg-deepest': '#0a0e1a',
      '--bg-surface': '#0f1528',
      '--bg-elevated': '#141c35',
      '--bg-active': '#1a2440',
      '--border-subtle': '#1e2d50',
      '--border-emphasis': '#2a3d60',
      '--accent-green': '#00e57a',
      '--accent-green-dim': '#004d30',
      '--accent-amber': '#f0a500',
      '--accent-red': '#e84545',
      '--accent-blue': '#5aa0ff',
      '--accent-purple': '#a88bff',
      '--accent-teal': '#00d4b3',
      '--text-primary': '#d0d8e8',
      '--text-dim': '#5a6a8a',
      '--text-muted': '#3a4a6a',
    },
    monaco: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'a88bff', fontStyle: 'bold' },
        { token: 'string', foreground: '00e57a' },
        { token: 'number', foreground: 'f0a500' },
        { token: 'type', foreground: '00d4b3' },
        { token: 'function', foreground: '5aa0ff' },
        { token: 'comment', foreground: '5a6a8a', fontStyle: 'italic' },
        { token: 'variable', foreground: 'd0d8e8' },
        { token: 'operator', foreground: 'd0d8e8' },
        { token: 'delimiter', foreground: '7888aa' },
      ],
      colors: {
        'editor.background': '#0a0e1a',
        'editor.foreground': '#d0d8e8',
        'editorCursor.foreground': '#00e57a',
        'editor.selectionBackground': '#1a3060',
        'editor.lineHighlightBackground': '#0f1528',
        'editorLineNumber.foreground': '#3a4a6a',
        'editorLineNumber.activeForeground': '#7888aa',
        'editorGutter.background': '#0a0e1a',
        'diffEditor.insertedTextBackground': '#00e57a18',
        'diffEditor.removedTextBackground': '#ff4a4a18',
        'diffEditor.insertedLineBackground': '#00e57a0d',
        'diffEditor.removedLineBackground': '#ff4a4a0d',
        'editorWidget.background': '#0f1528',
        'editorWidget.border': '#1e2d50',
        'input.background': '#0f1528',
        'input.border': '#1e2d50',
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#1e2d5080',
        'scrollbarSlider.hoverBackground': '#2a3d60',
        'scrollbarSlider.activeBackground': '#3a4d70',
      },
    },
    xterm: {
      background: '#0a0e1a',
      foreground: '#d0d8e8',
      cursor: '#00e57a',
      cursorAccent: '#0a0e1a',
      selectionBackground: '#1e2d50',
      black: '#0a0e1a',
      red: '#e84545',
      green: '#00e57a',
      yellow: '#f0a500',
      blue: '#5aa0ff',
      magenta: '#a88bff',
      cyan: '#00d4b3',
      white: '#d0d8e8',
    },
  },
};

export const themeIds = Object.keys(themes);
export const DEFAULT_THEME = 'mashed-dark';
